#ifndef TOKENH
#define TOKENH 1
#define EOFnumber 1
#define SEMInumber 2
#define COLONnumber 3
#define COMMAnumber 4
#define DOTnumber 5
#define LPARENnumber 6
#define RPARENnumber 7
#define LTnumber 8
#define GTnumber 9
#define EQnumber 10
#define MINUSnumber 11
#define PLUSnumber 12
#define TIMESnumber 13
#define DOTDOTnumber 14
#define COLEQnumber 15
#define LEnumber 16
#define GEnumber 17
#define NEnumber 18
#define IDnumber 19
#define ICONSTnumber 20
#define CCONSTnumber 21
#define SCONSTnumber 22
#define ANDnumber 23
#define ARRAYnumber 24
#define INTnumber 25
#define CONSTnumber 26
#define DIVIDEnumber 27
#define DOWNTOnumber 28
#define ELSEnumber 29
#define ELSIFnumber 30
#define ENDnumber 31
#define ENDIFnumber 32
#define ENDLOOPnumber 33
#define ENDRECnumber 34
#define EXITnumber 35
#define FORnumber 36
#define FORWARDnumber 37
#define FUNCTIONnumber 38
#define IFnumber 39
#define ISnumber 40
#define LOOPnumber 41 
#define NOTnumber 42
#define OFnumber 43
#define ORnumber 44
#define PROCEDUREnumber 45
#define PROGRAMnumber 46
#define RECORDnumber 47
#define REPEATnumber 48
#define RETURNnumber 49
#define THENnumber 50
#define TOnumber 51
#define TYPEnumber 52
#define UNTILnumber 53
#define VARnumber 54
#define WHILEnumber 55
#define FCONSTnumber 56
#define BEGINnumber 57
#define FLOATnumber 58
#define PRINTnumber 59
#endif
